import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  handbookSidebar: [
    {
      type: 'link',
      href: '/',
      label: 'LLM Inference Handbook',
      className: 'sidebar-home-link'
    },
    { type: 'autogenerated', dirName: '.' }
  ]
}

export default sidebars
